export { About } from "./about"
export { Skills } from "./skills"
export { Projects } from "./projects"
export { Experience } from "./experience"
export { Education } from "./education"
export { Contact } from "./contact"
